import RestError, { register } from './rest-error'

const errors = {}

errors.BadRequestError = register('BadRequestError', 400, 'Bad Request')
errors.UnauthorizedError = register('UnauthorizedError', 401, 'Unauthorized')
errors.PaymentRequiredError = register('PaymentRequiredError', 402, 'Payment Required')
errors.ForbiddenError = register('ForbiddenError', 403, 'Forbidden')
errors.NotFoundError = register('NotFoundError', 404, 'Not Found')
errors.MethodNotAllowedError = register('MethodNotAllowedError', 405, 'Method Not Allowed')
errors.NotAcceptableError = register('NotAcceptableError', 406, 'Not Acceptable')
errors.ProxyAuthenticationRequiredError = register('ProxyAuthenticationRequiredError', 407, 'Proxy Authentication Required')
errors.RequestTimeoutError = register('RequestTimeoutError', 408, 'Request Time-out')
errors.ConflictError = register('ConflictError', 409, 'Conflict')
errors.GoneError = register('GoneError', 410, 'Gone')
errors.LengthRequiredError = register('LengthRequiredError', 411, 'Length Required')
errors.PreconditionFailedError = register('PreconditionFailedError', 412, 'Precondition Failed')
errors.RequestEntityTooLargeError = register('RequestEntityTooLargeError', 413, 'Request Entity Too Large')
errors.RequesturiTooLargeError = register('RequesturiTooLargeError', 414, 'Request-URI Too Large')
errors.UnsupportedMediaTypeError = register('UnsupportedMediaTypeError', 415, 'Unsupported Media Type')
errors.RequestedRangeNotSatisfiableError = register('RequestedRangeNotSatisfiableError', 416, 'Requested Range Not Satisfiable')
errors.ExpectationFailedError = register('ExpectationFailedError', 417, 'Expectation Failed')
errors.ImATeapotError = register('ImATeapotError', 418, `I am a teapot`)
errors.UnprocessableEntityError = register('UnprocessableEntityError', 422, 'Unprocessable Entity')
errors.LockedError = register('LockedError', 423, 'Locked')
errors.FailedDependencyError = register('FailedDependencyError', 424, 'Failed Dependency')
errors.UnorderedCollectionError = register('UnorderedCollectionError', 425, 'Unordered Collection')
errors.UpgradeRequiredError = register('UpgradeRequiredError', 426, 'Upgrade Required')
errors.PreconditionRequiredError = register('PreconditionRequiredError', 428, 'Precondition Required')
errors.TooManyRequestsError = register('TooManyRequestsError', 429, 'Too Many Requests')
errors.RequestHeaderFieldsTooLargeError = register('RequestHeaderFieldsTooLargeError', 431, 'Request Header Fields Too Large')
errors.InternalServerError = register('InternalServerError', 500, 'Internal Server Error')
errors.NotImplementedError = register('NotImplementedError', 501, 'Not Implemented')
errors.BadGatewayError = register('BadGatewayError', 502, 'Bad Gateway')
errors.ServiceUnavailableError = register('ServiceUnavailableError', 503, 'Service Unavailable')
errors.GatewayTimeoutError = register('GatewayTimeoutError', 504, 'Gateway Time-out')
errors.HttpVersionNotSupportedError = register('HttpVersionNotSupportedError', 505, 'HTTP Version Not Supported')
errors.VariantAlsoNegotiatesError = register('VariantAlsoNegotiatesError', 506, 'Variant Also Negotiates')
errors.InsufficientStorageError = register('InsufficientStorageError', 507, 'Insufficient Storage')
errors.BandwidthLimitExceededError = register('BandwidthLimitExceededError', 509, 'Bandwidth Limit Exceeded')
errors.NotExtendedError = register('NotExtendedError', 510, 'Not Extended')
errors.NetworkAuthenticationRequiredError = register('NetworkAuthenticationRequiredError', 511, 'Network Authentication Required')
errors.BadDigestError = register('BadDigestError', 400, 'Bad Request')
errors.BadMethodError = register('BadMethodError', 405, 'Method Not Allowed')
errors.InternalError = register('InternalError', 500, 'Internal Server Error')
errors.InvalidArgumentError = register('InvalidArgumentError', 409, 'Conflict')
errors.InvalidContentError = register('InvalidContentError', 400, 'Bad Request')
errors.InvalidCredentialsError = register('InvalidCredentialsError', 401, 'Unauthorized')
errors.InvalidHeaderError = register('InvalidHeaderError', 400, 'Bad Request')
errors.MissingParameterError = register('MissingParameterError', 409, 'Conflict')
errors.NotAuthorizedError = register('NotAuthorizedError', 403, 'Forbidden')
errors.RequestExpiredError = register('RequestExpiredError', 400, 'Bad Request')
errors.RequestThrottledError = register('RequestThrottledError', 429, 'Too Many Requests')
errors.WrongAcceptError = register('WrongAcceptError', 406, 'Not Acceptable')

export default errors